# ci_service: circleci
# coverage_service: coveralls
xcodeproj: QuangDemoCircleCI.xcodeproj
workspace: QuangDemoCircleCI.xcworkspace
scheme: QuangDemoCircleCI
ignore:
  - Pods/*
  - QuangDemoCircleCITests/*
  - QuangDemoCircleCIUITests/*
  - ../**/*/Xcode*